### ISSUE TITLE
Node v16.13.0 is in Maintenance Mode

### ISSUE THREAD

**Issue by Krieke** [TREEcg/ldes-solid-server#3]
Any reason for sticking with Node v16.13.0 version, while there is already Node V18.12.0 LTS

**Comment by ajuvercr** [comment]
Yes, oidc-provider (dependency of CommunitySolidServer) is frozen at 7.10.6 which only supports v16 and below.
See https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1304
